FROM node:20.17

WORKDIR /app

COPY package.json /app/

RUN npm install -g pnpm
RUN pnpm install

COPY . /app/

ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_WEBSOCKET_URL
ARG JWT_SECRET

ENV NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
ENV NEXT_PUBLIC_WEBSOCKET_URL=${NEXT_PUBLIC_WEBSOCKET_URL}
ENV JWT_SECRET=${JWT_SECRET}

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]